### ISSUE TITLE
Add this funny rendition of  Sine melody but i did something

### ISSUE THREAD

**Issue by juanroman74454811** [SArpnt/bytebeat-composer#57]
Code: `a=(v=t/5*[2,4,2,4,2,4,2,4,2,5,2,4,3,3,2,1][t>>14&15]*((t>>11&3)+1),w=t/16*[1,2,1,2,3,2,1,4,5,4,6,3,2,4,1,3,3][t>>13&15]*((t>>13&3)+1),m=((Math.sin(v>>3)*64+6)+(Math.cos(w>>1)*63+6))/9+((Math.max(v)*64+64)+(Math.cos(w)*64+4))/8)^64,
b=Math.sin(t/[65,16,17,16,14,16,17,16,32,16,17,1,21,24,26,32][t>>14&15]*1)*3*((-t>>8&111)+1)+16,a+b`

**Comment by SArpnt** [comment]
please ask [stephanshi](https://github.com/SthephanShinkufag/bytebeat-composer) i don't curate the songs on here, i haven't even done anything with this in months, and i can't even figure out how to get github to tell me when people submit issues or pull requests on my projects
