### ISSUE TITLE
add my songs here pls

### ISSUE THREAD

**Issue by ghost** [SArpnt/bytebeat-composer#58]
## by: lunaboy_ (me)
[Wiw (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtEy0dKIUXJ0cnZxdXP38PTy9vH18w8IDAoOCQ0Lj4iMGpUZlRmVGZWhjUyMkmZNcWaeRomdnYWmlpmJtqGRRQ2QY6xVogUSNDU0Mraw1NQ3U9JRKk7MLchJDUosAZZbhoYGRqa1AA)
[my thing (my lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0ihRK7Gzs7CzK9HUNVKqBQA)
[44khz best. (my lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0ijR0i2xszM0qAGSZppKOkrFibkFOalBiSVAaRMTQwODWgA)
[danharaj fork (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtHXNawpUTUyNVWqBQA)
[beep beep (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtEyMrCz0yhRMzGwNLM3tDLSVDM0slCqBQA)
[uhh thing (by lunaboy_](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtHSiFEyNjYyMYtR0tQqsbMzNFDSUSpOzC3ISQ1KLAEqMTQwMKgFAA)
[fire sound (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKknM0yixsyvR1DJU0lEqTswtyEkNSiwBShkaGhiZ6ijlQtQFZ6bnpaYoOFWWpCalJpYo1QIA)
[vvvvvvvvvvvvvvvggggggggggggggggggggcccccccccccccc (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0qgrsbMz1NTS0DA0Mlcr0dIAEkABA03NOA0jE1OQiJG2hilY0EQTCJRqAQ)
[what is this song? (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtHVKIkrsbMzNNJU0lHKhQgGZ6bnpaYoOFWWpCalJpYo1QIA)
[plucker v2 tan go brrr (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKknM0yjRN7GzAxKaNSV2dkZKtQA)
[quiet song (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSSrQt0dIoUTMxsDSzt7Ay0dQqsbOz0DdXMzVWqgUA)
[fanfare sawtooth (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0ihRszC0NLIvUTMxsDQDUoYGRib2RlolViZAXKJmamhkD2KZ6IHENDCVGRrA1YG4FlolmnZ2RppaQKWGZsYWJvbGVkaaSrUA)
[rabid symphony sawtooth (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4hVDLTsNADPyXPbRJBG0TlApxiIT4g/5BcHZjbKzZbveG+Pe6uXBkJI/G6+f6JxCWGN5C7Yaua5q9okKgYKxuf1qhnE1MkguYCq8r0f/ZxVCgSXRDyY9SNahl5FLE3wEzoNbrld0T4RQpftKGlBJ/cVoSLTOzx30sx5VMyJtngbMysa/E5ixu5jo/eBvFG/YH4rl8+Fffa1OnqT/thnFsn8fX9tgPbXd+maZzeAq32fJ3vMzVT9L3p2H8vQM)
[squsinsaw stereo (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4fVDBbsMgDP2XSKMJcROMgSST6G1fgThUXQ9VpU5bmHro9u8zZN1WaaossP0sv/fgUu1envfVYxXm13efZEBQoPksWcNtz7mzfBPHtcoY5VJ3Qzm/bQxps0ElCKNwBubDae9JS8516o3qBkPOjDKMMMHEdKh/NmK2gkUk8y04Md60pGHenj0zyKDgNsZvHkB3xcrqKNBG9gHHw+7o8cn2dRJGTbbprXAE8+nN10lyFHlHH1w4zo1cKVS4Kvqa9csrHuo19ybPW/647AP/xmLXiSG2WXDx+f+cle+Ot+c741h9fgE)
[no no (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtE3tbMDEjUldnYmQJaWoVItAA)
[something:0, 32khz best (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0ihRK7GzM9TU0gBRxppKOkrFibkFOalBiSVAeWMjAwODWgA)
[______ (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0iipKbGzMzTS1NIA0hYgSlOpFgA)
[no array array song remixed (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4TU/LasMwEPwXgcKuvIklWVKdgnws9FAovZoc1g9oIbaLo0Kg9N+rxBR6mllmdmfnW/TLMIpHAXD5mNcIV2KMDbxwej+sy9c8bDSLcFV3+vpcGlsjInGEVKYCUtMYizJsLKCsUBmt8uCoi7e7UI2+hCRbp4+BTKhqd2r/9uwJUbm6cDX1ceV5WCZABfss+12ryXr/3yxv6QQsrQ+lK7o72qLfEHGX/ZhffNgbQeLC0+d5fOOUSzpntCYxbY2fzgunbuQkfn4B)
[square test (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKtHSKLGzM60BEhaaahYGSrUA)
[glissando but (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKrGzM6kBEqY1JVol+hpAlkUckDA01lSqBQA)
[our task is infinity reverse (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJS0tAtsbMzNFQDU0aaWmC+BYRrpqlqbKKlW6Jt4mqqD5RQMzGwNNVUqgUA)
[plucker v2 16khz (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSKrGzszXWAZIlNSVKOkrFibkFOalBiSVAOUMzAwODWgA)
[i dont know this thing (by lunaboy_)](https://sarpnt.github.io/bytebeat-composer/#v4Dc7LbgFxGEDxV5H/xhCRoRZiIRFv4A0mQ2JBKjo7aULrupzBKHWp1K3LKqoob3C+VzKrs/ydijIfszmVUJofG4cuPfq4DHhjyIh3xkyYMuODuY9PFixZsWbDF99s+WHHngO/HPnjxJkL/1y5SVVq8iKvUpeGNKUlbemILY64/kDYzBvltAenLM1KJiNBKxD0Gn1QIfVkFEuFXMawvKtYXNf15zs)
add them in "lunaboy_ - code lunaboy_ created"

**Comment by SArpnt** [comment]
please ask [stephanshi](https://github.com/SthephanShinkufag/bytebeat-composer) i don't curate the songs on here, i haven't even done anything with this in months, and i can't even figure out how to get github to tell me when people submit issues or pull requests on my projects

i'm not going to be changing the library for a while the project is a bit of a mess right now

**Comment by ghost** [comment]
ok
