### ISSUE TITLE
How do i record audio on Bytebeat Composer?

### ISSUE THREAD

**Issue by imthehappy** [SArpnt/bytebeat-composer#60]
So Dear SArpnt
I just want to let you know that i want to know how to record audio on Bytebeat Composer
Because i like that website and it has ton of audios to listen
So yeah i hope you respond! :)

**Comment by SArpnt** [comment]
sorry i didn't respond to this earlier, i disabled notifications on this repo at some point by mistake. i don't check here often, the website code has been moved to git.disroot.org and mirrored on codeberg.org

dollchan has a record button, and this site used to have one, but it would only record in bad quality, could only record as fast as it plays, and any lag would also get recorded. i ended up removing the button and i plan on adding it back later when it's added properly.

you're probably better off using some other audio recording program on your computer. windows might come with one, if not then just get a program like audacity. you could also just paste the code into dollchan.net, it uses a lot of the same code that mine does.
